#!/bin/bash
# Setup Gmail for OTP

echo "======================================"
echo "📧 Gmail Configuration Helper"
echo "======================================"
echo ""
echo "Follow these steps to set up Gmail for OTP:"
echo ""
echo "1️⃣  Go to: https://myaccount.google.com/apppasswords"
echo ""
echo "2️⃣  Sign in with your Gmail account"
echo ""
echo "3️⃣  Select:"
echo "   - App: Mail"
echo "   - Device: Windows Computer (or your device)"
echo ""
echo "4️⃣  Google will generate a 16-character password"
echo ""
echo "5️⃣  Copy that password"
echo ""
echo "6️⃣  Add to your .env file or Render environment:"
echo ""
echo "   SMTP_USER=your_email@gmail.com"
echo "   SMTP_PASS=<16_char_password>"
echo "   SMTP_HOST=smtp.gmail.com"
echo "   SMTP_PORT=587"
echo "   EMAIL_FROM=\"Your App <your_email@gmail.com>\""
echo ""
echo "======================================"
echo "⚠️  Important Notes:"
echo "======================================"
echo "• Use App Password, NOT your regular Gmail password"
echo "• App Password only works with 2-Step Verification enabled"
echo "• Keep the password secret - don't share in public repos"
echo "• For production, use Render's secure environment variables"
echo ""
echo "✅ Once configured, OTP emails will send automatically!"
echo ""
